# Generated by Django 5.1.2 on 2024-11-26 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('marcado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('temperatura_ideal', models.CharField(max_length=50)),
                ('tipo_solo', models.CharField(max_length=100)),
                ('rotacao_cultivo', models.CharField(max_length=100)),
                ('umidade_ideal', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Culturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizante', models.CharField(max_length=100)),
                ('imagem', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Semente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semente', models.CharField(max_length=100)),
                ('imagem', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('REGA', 'Rega'), ('COLHEITA', 'Colheita')], max_length=10)),
                ('data_ultima_acao', models.DateField()),
                ('concluida', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default='', max_length=254, null=True, unique=True)),
                ('senha', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rotacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cultura', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calendario.culturas')),
            ],
        ),
    ]
