# Generated by Django 5.1.1 on 2024-11-26 21:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='data_ultima_acao',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='nome',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(default='Nova Tarefa'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='dia',
            field=models.IntegerField(default=1),
        ),
    ]
