# Generated by Django 5.1.2 on 2024-10-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizante', models.CharField(max_length=100)),
                ('imagem', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Semente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semente', models.CharField(max_length=100)),
                ('imagem', models.URLField(max_length=300)),
            ],
        ),
    ]
