# Generated by Django 5.1.1 on 2024-10-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jatoba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('REGA', 'Rega'), ('COLHEITA', 'Colheita')], max_length=10)),
                ('data_ultima_acao', models.DateField()),
                ('concluida', models.BooleanField(default=False)),
            ],
        ),
    ]
