# Generated by Django 5.1.1 on 2024-10-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jatoba', '0002_tarefa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='', max_length=255),
        ),
    ]
