# Generated by Django 5.1.2 on 2024-10-11 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jatoba', '0003_remove_usuario_nome_usuario_email_usuario_senha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkbox',
        ),
    ]
