# Generated by Django 5.1.1 on 2024-10-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jatoba', '0004_delete_checkbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('temperatura_ideal', models.CharField(max_length=50)),
                ('tipo_solo', models.CharField(max_length=100)),
                ('rotacao_cultivo', models.CharField(max_length=100)),
                ('umidade_ideal', models.CharField(max_length=50)),
            ],
        ),
    ]
