# Generated by Django 5.1.1 on 2024-11-24 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jatoba', '0006_checklistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizante', models.CharField(max_length=100)),
                ('imagem', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Semente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semente', models.CharField(max_length=100)),
                ('imagem', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Rotacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cultura', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jatoba.culturas')),
            ],
        ),
    ]
