# Generated by Django 5.1.1 on 2024-11-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jatoba', '0006_checklistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='data_ultima_acao',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='frequencia_rega',
            field=models.IntegerField(default=3),
        ),
    ]
