# Generated by Django 5.1.1 on 2024-11-03 23:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jatoba', '0007_remove_tarefa_data_ultima_acao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_ultima_acao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='frequencia_rega',
            field=models.IntegerField(default=1),
        ),
    ]
