# Generated by Django 5.1.1 on 2024-11-14 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jatoba', '0008_tarefa_data_ultima_acao_alter_tarefa_frequencia_rega'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='concluida',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='data_ultima_acao',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='frequencia_rega',
        ),
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=255)),
                ('data_lembrete', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
