# Generated by Django 5.1.1 on 2024-11-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jatoba', '0009_remove_tarefa_concluida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lembrete',
            name='data_lembrete',
            field=models.DateTimeField(),
        ),
    ]
