name: Build and deploy Python app to Azure Web App - djangodeploy2

on:
  push:
    branches:
      - deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Cleaning testing files
        run: |
          rm db.sqlite3 || true
          rm .env || true
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      - name: Run Django tests
        run: |
          source venv/bin/activate
          python manage.py test

      - name: Zip artifact for deployment
        run: |
          zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Create .env file
        run: |
          echo "DEBUG=0" >> .env
          echo "ALLOWED_HOSTS=your_domain.com" >> .env

      - name: Apply Django Migrations
        run: |
          source venv/bin/activate
          python manage.py migrate

      - name: Collect Static Files
        run: |
          source venv/bin/activate
          python manage.py collectstatic --noinput

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'djangodeploy2'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D51C3E4C02C5422BA34C7BA2BC9E8033 }}

      - name: Verify Deployment
        run: |
          curl -v ${{ steps.deploy-to-webapp.outputs.webapp-url }}
